version: "3.8"

services:
  ravendb:
    extends:
      file: docker-compose-services.yml
      service: ravendb
  substrate:
    extends:
      file: docker-compose-services.yml
      service: substrate
  api:
    extends:
      file: docker-compose-services.yml
      service: api
  tests:
    build:
      context: .
      target: test
    environment:
      - WAIT_HOSTS=api:5000
      - WAIT_TIMEOUT=90
    volumes:
      - ./integration-test-results/:/source/engi-tests/TestResults/

volumes:
  integration-test-results: