version: "3.8"

services:
  ravendb:
    container_name: ravendb
    image: ravendb/ravendb:5.4-ubuntu-latest
    ## For mac M1, use this image
    # image: ravendb/ravendb:5.4-ubuntu-arm64v8-latest
    environment:
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_ServerUrl_Tcp=38888
  substrate:
    container_name: substrate-node
    image: 163803973373.dkr.ecr.us-west-2.amazonaws.com/blockchain-testnet:testnet
    command: --dev --pruning archive --rpc-external --ws-external --charlie
  api:
    build: 
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=CI
      - ASPNETCORE_URLS=http://*:8000
      - SUBSTRATE__HTTPURL=http://substrate:9933
      - SUBSTRATE__WSURL=ws://substrate:9944
      - WAIT_HOSTS=substrate:9933, substrate:9944, ravendb:8080, ravendb:38888
      - WAIT_TIMEOUT=300
