version: "3.8"

services:
  ravendb:
    extends:
      file: docker-compose-services.yml
      service: ravendb
  substrate:
    extends:
      file: docker-compose-services.yml
      service: substrate
  api:
    extends:
      file: docker-compose-services.yml
      service: api
  docs:
    build:
      context: ./engi-docs
    environment:
      - WAIT_HOSTS=api:5000
    volumes:
      - ./engi-server/wwwroot/docs/:/docs/public/

volumes:
  docs: